config/routes.rb
Rails.application.routes.draw do
	root to: "pages#home"

resources :stylists

resources :clients

resources :reservations

resources :sessions, only: [:create, :new]

get "/location", to: "pages#location", as: "location"

get "/client_stylist", to: "pages#client_stylist", as: "client_stylist"

delete "/sessions", to: "sessions#destroy", as: "logout"

#OPTIMIZE: RESTful routes always are plural
#OPTIMIZE: If it is to create a reservation then a `post` to `/reservations` would make more sense
post "/stylist/:id", to: "reservations#create", as: "create_reservation"

#TODO: Nice routes, overall!

end

app/models/client.rb
class Client < ActiveRecord::Base

	 has_many :reservations  
  	 has_many :stylists, through: :reservations

	has_secure_password

end

app/models/message.rb
class Message < ActiveRecord::Base

	belongs_to :stylist
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :client
	belongs_to :stylist

after_create :send_message

def send_message
	stylist = self.stylist
	client = self.client
	message = Message.create(to: stylist.first_name, from: client.first_name, body: "Hello, I would love to book an appointment with you!", stylist_id: stylist.id)
end

end

app/models/stylist.rb
class Stylist < ActiveRecord::Base
	validates :email, uniqueness: true
	has_secure_password

	has_many :messages
	has_many :reservations  
  	has_many :clients, through: :reservations

	def self.confirm(params)
		@stylist = Stylist.find_by({email: params[:email]})
		@stylist.try(:authenticate, params[:password])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionHelper
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
    render :index
  end

def new
     @client = Client.new
    render :new
  end
def create
    #OPTIMIZE: I believe you have a helper method for this at the bottom of this file
    client_params = params.require(:client).permit(:first_name, :last_name, :email, :password)
     @client = Client.new(client_params)
    if @client.save
      login(@client)

      redirect_to edit_client_path(@client)
    else
      render :show
    end
#actually want the above page to redirect to another form welcome page
#this other form will have all the other db details
  end

  def edit
    @client = Client.find(params[:id])
    render :edit
  end


def update
    #TODO: Nice only allowing a user to update themselves and note others!
    # authorization check
    if current_user.id == params[:id].to_i
      # allow update
      current_user.update_attributes(client_params)
      redirect_to current_user
    else
      # drop them back on the edit page
      redirect_to edit_client_path(current_user)
    end
    # pull out params
    # find the stylist (current_user)
    # .update_attributes

    # redirect_to "/stylists/#{@stylist.id}"
    # <%= @stylist.school %>
  end
def show
    @client = Client.find(params[:id])
    render :show
  end

def client_params
  params.require(:client).permit(:headshot, :phone, :bio, :hair_goal, :last_salon_visit,
    :service, :allergies, :referred_by, :favorite_products, :birthday, :hobbies)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		render :home
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


	def index
    @reservations = Reservation.all
    render :index
  end

def new
     @reservation = Reservation.new
    render :new
  end

def create
    #i don't think this isn't going to matter
    @reservation = Reservation.create(client_id:current_user.id, stylist_id:params[:id])

    redirect_to root_path
#actually want the above page to redirect to another form welcome page 
#this other form will have all the other db details
  end





def show
    @reservation = reservation.find(params[:id])
    render :show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		#we made this generic
		render :new
	end

	def create
	user = Client.find_by(email: params[:email]) || Stylist.find_by(email: params[:email]) 
	login(user)
    if user.class.name == 'Client'
      redirect_to current_user# client show page (with current_user)
    elsif
      redirect_to current_user# stylist show page (with current_user)
    else
    	# error handling
      render :new
    end
	# find the stylist by email (validate uniquness of email)
	# `stylist.confirm` to check if password is correct
	# if password is correct, login the stylist and redirect to the current_stylist profile page
	# else render new again
	end

	def destroy
		logout
		redirect_to root_path
	end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  # grab the users
  def index
    @stylists = Stylist.all
    render :index
  end

def new
     @stylist = Stylist.new
    render :new
  end

def create
    stylist_params = params.require(:stylist).permit(:first_name, :last_name, :email, :password)
    @stylist = Stylist.new(stylist_params)
    if @stylist.save
      login(@stylist)
      redirect_to edit_stylist_path(@stylist)
    else
      render :new
    end
    # redirect_to "/stylists/#{@stylist.id}/edit"

    # redirect_to "/stylists/#{@stylist.id}"


    #didn't got to that stylists id in url
#actually want the above page to redirect to another form welcome page 
#this other form will have all the other db details
  end

  def edit
    @stylist = current_user
    render :edit
  end

  def update
    # authorization check
    if current_user.id == params[:id].to_i
      # allow update
      current_user.update_attributes(stylist_params)
      redirect_to current_user
    else
      # drop them back on the edit page
      redirect_to edit_stylist_path(current_user)
    end
    # pull out params
    # find the stylist (current_user)
    # .update_attributes

    # redirect_to "/stylists/#{@stylist.id}"



    # <%= @stylist.school %>
  end

def show
    @stylist = Stylist.find(params[:id])
    render :show
  end

  
private

  def stylist_params
    params.require(:stylist).permit(:speciality, :salon, :school, :bio, :headshot, :license)
  end

end

	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def login(user)
    if user.class.name == 'Stylist'
      session[:user_id] = user.id
      @current_user = Stylist.find_by_id(user.id)
    else
      session[:user_id] = user.id
      @current_user = Client.find_by_id(user.id)
    end
  end

  def current_user
    @current_user ||= Client.find_by_id(session[:user_id]) || Stylist.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to "/sign_in"
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/clients/edit.html.erb
<div class ="align stlClP">


<%= form_for @client do |f| %>
  <div>
    <%= f.text_field :hair_goal, placeholder: "Hair goal" %>

  </div>
  <div>
    <%= f.text_field :last_salon_visit, placeholder: "Last Salon Visit" %>
  </div>
  <div>
    <%= f.text_field :service, placeholder: "Services Recieved" %>
  </div>
 <div>
    <%= f.text_field :allergies, placeholder: "Allergies " %>
  </div>
  <div>
    <%= f.text_field :birthday, placeholder: "Birthday" %>
  </div>
<div>
 <%= f.text_field :referred_by, placeholder: "Referred by" %>
  </div>

   <div>
    <%= f.text_field :headshot, placeholder: "Headshot" %>
  </div>
  <%= f.submit "Submit" %>
<% end %>
</div>

app/views/clients/index.html.erb
<h1>EMPRESSED</h1>
<!-- #example text below
 -->
 <div>
There are currently <%= @clients.length %> signed_up
</div>

app/views/clients/new.html.erb
<div class ="align stlClP">


<h1>Sign Up</h1>

<%= form_for @client do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password", class: "sPassword2"%>
  </div>

  <%= f.submit "Sign Up" %>
<% end %>

</div>

app/views/clients/show.html.erb
<div id= "container">

<h1><%= @client.first_name %></h1>

  <div class="headShotContain ">

 <%= image_tag(@client.headshot,class: "box")  %>

 <div class= "credits">

 <h2 class= "creditsh2">Credentials</h2>

  <p class ="creditsP"> HAIR GOAL: <%= @client.hair_goal %></p>
  <p class ="school creditsP"> LAST SALON VISIT <%= @client.last_salon_visit%></p>

  

 </div>

 <div class= "skillsID">

 <h1 class="cardh2">CLIENT CARD</h1>

  <p class ="cardP"> EMAIL: <%= @client.email %></p>
  <p class ="cardP"> PHONE: <%= @client.phone %></p>
  <p class ="cardP">ALLERGIES: <%= @client.allergies %></p>
  <p class ="cardP">BIRTHDAY: <%= @client.birthday %></p>
  <p class ="cardP">REFERRED BY: <%= @client.referred_by %></p>


 </div>

 </div>





<%= @client.bio %>
  
 <!--  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum quae, modi dolor deserunt aspernatur cum neque molestiae, eos officiis impedit possimus? Deleniti non laborum, eos aliquam impedit? Nemo doloremque, molestiae.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero natus modi inventore impedit vero porro pariatur ut illum quisquam consequatur, in dicta adipisci aliquam velit cupiditate quibusdam commodi rem corporis.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero natus modi inventore impedit vero porro pariatur ut illum quisquam consequatur, in dicta adipisci aliquam velit cupiditate quibusdam commodi rem corporis. -->
</p>


</div>


























</div>





<!-- #decorate this page the way you would want your homepage to be 
#search the pictures you put in your phone

#signin with a link to sign in
#two tabs client / Client

#icebox - video description of service 
#main picture a video of client at work  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmpressedApp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<ul>
  <li><%= link_to "HOME", root_path %></li>
  
 
  <li><a href="#skills">ABOUT US</a></li>
  <li><%= link_to "STYLIST", stylists_path %></li>

     <li><%= link_to "SKILLS", root_path %></li>

 
  <% if !current_user %>
      <li><%= link_to "LOGIN", new_session_path%></li>

<!--     <li><a href="#login">LOGIN</a></li>
 -->  <% else %>
    <li><%= link_to "LOGOUT", logout_path, method: :delete %></li>
  <% end %> 
  
  <li><%= link_to "LOCATION", location_path%></li>


  <li><a href="#contact">CONTACT US</a></li>
 </ul>
   
<div id= "container">

<%= yield %>

</div>

 <footer>
            <p class="footer cform">Copyrighted 2016. All rights reserved in Empressed.</a></p>
    </footer>


</body>

<script src ="https://code.jquery.com/jquery-2.2.1.min.js"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js"></script>
</html>

app/views/pages/client_stylist.html.erb
<div class ="align stlClP">

<h1 class = "stlClP" >Are you a Stylist or a Future client</h1>



<div class = "signUpSCDiv">


<%= link_to "Stylist", new_stylist_path, class: "signUpSC" %>

<%= link_to "Client", new_client_path, class: "signUpSC" %>

</div>

</div>

app/views/pages/home.html.erb
    <div class ="video">
<h1 id ="homeC1">"BOOK ME EMPRESSED!"</h1>
<h1 id ="homeC2">Where hair Stylist and Clients Meet</h1>
  <%= submit_tag "SIGN IN", class: "homeC3" %>

<%= video_tag("whipmyhair.mp4", autoplay: :autoplay, autobuffer: true, width: "100%" ) %>

   </div>

   

  <section class ="aboutUs"> 

          <h3 class="aboutText">
         <span>ABOUT US</span> - 
This is an app that is meant to connect clients and Stylist.
As a hairstylist or any freelance job, building clientle is one of 
the most important things. 

This app is not to build clientele so much but to maintain the clients 
you have built.

It solves the problem of cancellations by allowing a client to reserve
an appoint with a stylist.

Right now this reservation process only sends a message to the stylist
that a particular client would like to book with them.

Later the a client will be reserving that appointment with a credit
card deposit.</h3>

         
      </div>



      </section>



  <div class="boxContain" id ="basic-waypoint">

 <div class="box boxEx">
 <p class="boxP">HAIR CUTS</p>
 </div>

  <div class="box boxEx">
 <p class="boxP">COLOR</p>


  </div>

 <div class="box boxEx">

 <p class="boxP">UPDOS</p>

 </div>

</div>

  <div class="boxContain" id="basic-waypoint2">

 <div class="box boxEx">

 <p class="boxP">BRAIDS</p>

 </div>

  <div class="box boxEx">

 <p class="boxP">EXTEN SIONS</p>

</div>

 <div class="box boxEx">
   

    <p class="boxP">BARBERS</p>

 </div>

</div>

<!-- contact us form -->

<h1 class = "align space">Contact Us</h1>
  <div>
     <form id="contact-form" class ="align" method="POST" action="processForm.php" name="ContactForm">
    
   

      <p class="inputfield cform"><label for="subject"></label></p> 
                <input type="text" id="name" name="name" placeholder="Subject" style="color: #fff;" onfocus="if (this.value == '90') {this.value=''; this.style.color='#000';}" required tabindex="1" /> 
    
        <p class="inputfield cform"><label for="message"></label></p> 
                <textarea name="message" id="message" tabindex="2"></textarea> 
            
      <p class="inputfield cform"><label for="name"></label></p> 
                <input type="text" id="name" name="name" placeholder="First and last name" style="color: #fff;" onfocus="if (this.value == '90') {this.value=''; this.style.color='#000';}" required tabindex="3" /> 
                 
        <p class="inputfield cform"><label for="email"></label></p> 
                <input type="text" id="email" name="email" placeholder="yourname@domain.com" required tabindex="4" />
                
        <input name="submit" type="submit" id="submit" tabindex="5" value="Submit" />
     </form>
  
 
  </div>
  

app/views/pages/location.html.erb
<div class = "align down">


<h1 class ="larger">Search By Location </h1>

<h1 class ="larger">Coming Soon</h1>


</div>

app/views/reservations/edit.html.erb
<h1>Reservations Edit page </h1>

app/views/reservations/index.html.erb
<h1>Reservations Home Page </h1>

<div>
There are currently <%= @reservations.length %> scheduled
</div>

app/views/reservations/new.html.erb
<h1>Reservations New page </h1>

app/views/reservations/show.html.erb
<h1>Reservations Show page </h1>

app/views/stylists/edit.html.erb
<h1>This is the stylists edit page</h1>




<div>
  Welcome, <%= @stylist.first_name %> 
</div>

#This would be the page with the new input form
#how would I link this info.. would I make a new create controller or add the info the the already made create folder 

<%= form_for @stylist do |f| %>
  <div>
    <%= f.text_field :speciality, placeholder: "Speciality i.e color" %>
#icebox
#how to make this when they start typing options come up
  </div>
  <div>
    <%= f.text_field :salon, placeholder: "Salon" %>
  </div>
  <div>
    <%= f.text_field :school, placeholder: "School" %>
  </div>
 <div>
    <%= f.text_field :bio, placeholder: "Brief Description " %>
  </div>
  <div>
    <%= f.text_field :headshot, placeholder: "Headshot" %>
#how to make upload photo link
  </div>
<div>
 <%= f.text_field :license, placeholder: "Upload license" %>
  </div>
#confirm password
  <%= f.submit "Submit" %>
<% end %>

app/views/stylists/index.html.erb
<h1>Stylists</h1>

<div class ="flex">






<% @stylists.each do |stylist| %>

<div class = "allContain">


     <%= image_tag(stylist.headshot,class: "indexPic")  %>

<div class ="right">
  <p class="sIndex">Artist: <%= link_to stylist.first_name, stylist_path(stylist) %></p>
  <p class="sIndex">School: <%= stylist.school %></p>
  <p class="sIndex">Salon: <%= stylist.salon %></p>

</div>

</div>
<% end %>

</div>




    

app/views/stylists/new.html.erb
<h1>Sign Up</h1>




<%= form_for @stylist do |f| %>
  <div>
  <!-- fist name not working -->
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
 <%= f.password_field :password, placeholder: "Password", class: "sPassword2" %>
  </div>
<!-- #confirm password -->
  <%= f.submit "Sign Up" %>
<% end %>

<!-- #render a page that has them fill out the rest of their profile
#stated this in redirect_to page -->

app/views/stylists/show.html.erb
<div id= "container">

<h1><%= @stylist.first_name %></h1>

  <div class="headShotContain ">

  <%= image_tag(@stylist.headshot,class: "box")  %>

 <div class= "credits">

 <h2 class= "creditsh2">Credentials</h2>

  <p class ="creditsP"> Salon: <%= @stylist.salon %></p>
  <p class ="school creditsP"> School: <%= @stylist.school %></p>

  <div class = "bookMe">

<%= link_to "BOOK ME", create_reservation_path(@stylist), method: :post %>
</div>

 </div>

 <div class= "skillsID">

 <h2 class="skillsh2">Skills</h2>

  <p class ="skillsP"> Cut</p>
  <p class ="skillsP"> Updos</p>
  <p class ="skillsP">Makeup</p>
  <p class ="skillsP">Nail Design</p>

 </div>

 </div>

<h3>Specialty: <%= @stylist.speciality %></h3>

<div class ="bioContain">

<h2>About Me</h2>

<p class ="sShow">



<%= @stylist.bio %>
  
 <!--  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum quae, modi dolor deserunt aspernatur cum neque molestiae, eos officiis impedit possimus? Deleniti non laborum, eos aliquam impedit? Nemo doloremque, molestiae.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero natus modi inventore impedit vero porro pariatur ut illum quisquam consequatur, in dicta adipisci aliquam velit cupiditate quibusdam commodi rem corporis.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero natus modi inventore impedit vero porro pariatur ut illum quisquam consequatur, in dicta adipisci aliquam velit cupiditate quibusdam commodi rem corporis. -->
</p>


</div>

<div class="galleryContain">

<h2>Portfolio</h2>
<%= image_tag("img1.jpg", class: "galleryImg") %>
<%= image_tag("img2.jpg", class: "galleryImg") %>
<%= image_tag("img3.jpg", class: "galleryImg") %>
<%= image_tag("img1.jpg", class: "galleryImg") %>


</div>



<h1>CLIENTS THAT WANT TO BOOK</h1>

<% @stylist.messages.each do |message| %>

<div class = "allContain">

<%= message.from %>
<%= message.body %>

</div>
<%end%>







<!-- #decorate this page the way you would want your homepage to be 
#search the pictures you put in your phone

#signin with a link to sign in
#two tabs Stylist / Client

#icebox - video description of service 
#main picture a video of stylist at work  -->